name: "vercel-cypress"
description: "Run Cypress tests against a Vercel deployment"
branding:
  icon: "alert-circle"
  color: "green"
inputs:
  vercel-token:
    description: "Vercel API token"
    required: true
  team:
    description: "Team name"
    required: true
  options:
    description: "Cypress options"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.vercel-token }}
    - ${{ inputs.team }}
    - ${{ inputs.options }}
